create table if not exists public.quizzes (
    quiz_id text primary key,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    questions jsonb not null
);

create table if not exists public.quiz_results (
    id bigint generated by default as identity primary key,
    quiz_id text not null references public.quizzes(quiz_id) on delete cascade,
    participant_name text not null,
    submitted_at timestamptz not null default now(),
    total double precision not null,
    answers jsonb not null,
    scores jsonb not null
);

create index if not exists quiz_results_quiz_id_submitted_at_idx
    on public.quiz_results (quiz_id, submitted_at);

-- Die App verwendet ausschließlich den geheimen service_role-Key auf dem Server.
alter table public.quizzes enable row level security;
alter table public.quiz_results enable row level security;

revoke all on table public.quizzes from anon, authenticated;
revoke all on table public.quiz_results from anon, authenticated;
